services:
  bitcoin:
    image: "bitcoin"
    build:
      context: .
      dockerfile: Dockerfile.bitcoin
    entrypoint: bash -c "./start-bitcoin.sh"
    secrets:
      - username
      - password
    configs:
      - port
  lightning:
    image: "lightning"
    build:
      context: .
      dockerfile: Dockerfile.lightning
    entrypoint: bash -c "./start-lightning.sh"
    depends_on:
      - bitcoin
    deploy:
      replicas: 6
    secrets:
      - username
      - password
    configs:
      - port

secrets:
  username:
    file: secrets/username.txt
  password:
    file: secrets/password.txt

configs:
  # Bitcoin node port number for its RPC API
  # This port is not exposed to host
  port:
    file: configs/port.txt
